//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestCurrencyNumbersToWordsWCFService.CurrencyServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CurrencyNumbersToWords", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class CurrencyNumbersToWords : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyNumber {
            get {
                return this.CurrencyNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyNumberField, value) != true)) {
                    this.CurrencyNumberField = value;
                    this.RaisePropertyChanged("CurrencyNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CurrencyServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConvertCurrencyNumbersToWords", ReplyAction="http://tempuri.org/IService/ConvertCurrencyNumbersToWordsResponse")]
        UnitTestCurrencyNumbersToWordsWCFService.CurrencyServiceReference.CurrencyNumbersToWords ConvertCurrencyNumbersToWords(string currencyNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConvertCurrencyNumbersToWords", ReplyAction="http://tempuri.org/IService/ConvertCurrencyNumbersToWordsResponse")]
        System.Threading.Tasks.Task<UnitTestCurrencyNumbersToWordsWCFService.CurrencyServiceReference.CurrencyNumbersToWords> ConvertCurrencyNumbersToWordsAsync(string currencyNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : UnitTestCurrencyNumbersToWordsWCFService.CurrencyServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<UnitTestCurrencyNumbersToWordsWCFService.CurrencyServiceReference.IService>, UnitTestCurrencyNumbersToWordsWCFService.CurrencyServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UnitTestCurrencyNumbersToWordsWCFService.CurrencyServiceReference.CurrencyNumbersToWords ConvertCurrencyNumbersToWords(string currencyNumber) {
            return base.Channel.ConvertCurrencyNumbersToWords(currencyNumber);
        }
        
        public System.Threading.Tasks.Task<UnitTestCurrencyNumbersToWordsWCFService.CurrencyServiceReference.CurrencyNumbersToWords> ConvertCurrencyNumbersToWordsAsync(string currencyNumber) {
            return base.Channel.ConvertCurrencyNumbersToWordsAsync(currencyNumber);
        }
    }
}
